pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: docs"
      - "status-success=ci/circleci: py27"
      - "status-success=ci/circleci: py36"
      - "status-success=ci/circleci: py37"
      - "status-success=ci/circleci: py38"
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
