pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - check-success=test
    actions:
      queue:
        name: default

  - name: automatic merge from maintainer
    conditions:
      - base=main
      - author=jd
      - check-success=test
    actions:
      queue:
        name: default

  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}


queue_rules:
  - name: default
    conditions: []
