pull_request_rules:
  - name: automatic merge
    conditions:
      - base=master
      - "status-success=ci/circleci: test"
      - status-success=test
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
  - name: automatic merge from maintainer
    conditions:
      - author=jd
      - status-success=test
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"
