pull_request_rules:
  - name: automatic merge
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
      - and: &CheckRuns
          - "check-success=pep8"
          - "check-success=test (3.7)"
          - "check-success=test (3.8)"
          - "check-success=test (3.9)"
          - "check-success=test (3.10)"

    actions:
      queue:
        name: default

  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}


queue_rules:
  - name: default
    conditions: []
