version: 2.1

commands:
  tox:
    parameters:
      target:
        type: string
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            tox -e << parameters.target >>

jobs:
  pep8:
    docker:
      - image: circleci/python:3.8
    steps:
      - tox: {target: pep8}
  docs:
    docker:
      - image: circleci/python:3.8
    steps:
      - tox: {target: docs}
  py27:
    docker:
      - image: circleci/python:2.7
    steps:
      - tox: {target: py27}
  py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - tox: {target: py36}
  py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - tox: {target: py37}
  py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - tox: {target: py38}


workflows:
  version: 2

  test:
    jobs:
      - pep8
      - py27
      - py36
      - py37
      - py38
      - docs
