name: CI
permissions: read-all

on:
  pull_request:
    branches:
      - main
      - devs/**

jobs:
  test:
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Python 🔧
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python }}

      - name: Test 🔍
        run: |
          pip install -r requirements-uv.txt
          uv sync
          uv run poe linters
          uv run poe test
          uv build
